import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import LayoutComponent from "@/layout/layout.component";
import ThemeRegistry from "@ui/shared-resources/themes/ThemeRegistry";
import Script from "next/script";
import { AOSInit } from "@/shared/base/AOSInit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
        <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></Script>
      </head>
      <AOSInit />
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui-theme" }}>
          <LayoutComponent>{children}</LayoutComponent>
        </ThemeRegistry>
      </body>
    </html>
  );
}
